# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tahmid/code_editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tahmid/code_editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tahmid/code_editor/CMakeFiles /home/tahmid/code_editor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tahmid/code_editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CodeEditor

# Build rule for target.
CodeEditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeEditor
.PHONY : CodeEditor

# fast build rule for target.
CodeEditor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/build
.PHONY : CodeEditor/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named CodeEditor_autogen_timestamp_deps

# Build rule for target.
CodeEditor_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeEditor_autogen_timestamp_deps
.PHONY : CodeEditor_autogen_timestamp_deps

# fast build rule for target.
CodeEditor_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor_autogen_timestamp_deps.dir/build.make CMakeFiles/CodeEditor_autogen_timestamp_deps.dir/build
.PHONY : CodeEditor_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named CodeEditor_autogen

# Build rule for target.
CodeEditor_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeEditor_autogen
.PHONY : CodeEditor_autogen

# fast build rule for target.
CodeEditor_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor_autogen.dir/build.make CMakeFiles/CodeEditor_autogen.dir/build
.PHONY : CodeEditor_autogen/fast

CodeEditor_autogen/mocs_compilation.o: CodeEditor_autogen/mocs_compilation.cpp.o
.PHONY : CodeEditor_autogen/mocs_compilation.o

# target to build an object file
CodeEditor_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/CodeEditor_autogen/mocs_compilation.cpp.o
.PHONY : CodeEditor_autogen/mocs_compilation.cpp.o

CodeEditor_autogen/mocs_compilation.i: CodeEditor_autogen/mocs_compilation.cpp.i
.PHONY : CodeEditor_autogen/mocs_compilation.i

# target to preprocess a source file
CodeEditor_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/CodeEditor_autogen/mocs_compilation.cpp.i
.PHONY : CodeEditor_autogen/mocs_compilation.cpp.i

CodeEditor_autogen/mocs_compilation.s: CodeEditor_autogen/mocs_compilation.cpp.s
.PHONY : CodeEditor_autogen/mocs_compilation.s

# target to generate assembly for a file
CodeEditor_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/CodeEditor_autogen/mocs_compilation.cpp.s
.PHONY : CodeEditor_autogen/mocs_compilation.cpp.s

src/editor.o: src/editor.cpp.o
.PHONY : src/editor.o

# target to build an object file
src/editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/editor.cpp.o
.PHONY : src/editor.cpp.o

src/editor.i: src/editor.cpp.i
.PHONY : src/editor.i

# target to preprocess a source file
src/editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/editor.cpp.i
.PHONY : src/editor.cpp.i

src/editor.s: src/editor.cpp.s
.PHONY : src/editor.s

# target to generate assembly for a file
src/editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/editor.cpp.s
.PHONY : src/editor.cpp.s

src/filemanager.o: src/filemanager.cpp.o
.PHONY : src/filemanager.o

# target to build an object file
src/filemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/filemanager.cpp.o
.PHONY : src/filemanager.cpp.o

src/filemanager.i: src/filemanager.cpp.i
.PHONY : src/filemanager.i

# target to preprocess a source file
src/filemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/filemanager.cpp.i
.PHONY : src/filemanager.cpp.i

src/filemanager.s: src/filemanager.cpp.s
.PHONY : src/filemanager.s

# target to generate assembly for a file
src/filemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/filemanager.cpp.s
.PHONY : src/filemanager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/syntax.o: src/syntax.cpp.o
.PHONY : src/syntax.o

# target to build an object file
src/syntax.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/syntax.cpp.o
.PHONY : src/syntax.cpp.o

src/syntax.i: src/syntax.cpp.i
.PHONY : src/syntax.i

# target to preprocess a source file
src/syntax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/syntax.cpp.i
.PHONY : src/syntax.cpp.i

src/syntax.s: src/syntax.cpp.s
.PHONY : src/syntax.s

# target to generate assembly for a file
src/syntax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/syntax.cpp.s
.PHONY : src/syntax.cpp.s

src/ui.o: src/ui.cpp.o
.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeEditor.dir/build.make CMakeFiles/CodeEditor.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CodeEditor_autogen"
	@echo "... CodeEditor_autogen_timestamp_deps"
	@echo "... run"
	@echo "... CodeEditor"
	@echo "... CodeEditor_autogen/mocs_compilation.o"
	@echo "... CodeEditor_autogen/mocs_compilation.i"
	@echo "... CodeEditor_autogen/mocs_compilation.s"
	@echo "... src/editor.o"
	@echo "... src/editor.i"
	@echo "... src/editor.s"
	@echo "... src/filemanager.o"
	@echo "... src/filemanager.i"
	@echo "... src/filemanager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/syntax.o"
	@echo "... src/syntax.i"
	@echo "... src/syntax.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

